name: Test and Deploy
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
				  postgresql version: '14.4'
          postgresql db: nc_games_test
          postgresql user: mr_testerson
          postgresql password: passw0rd
      - name: Run Integration Tests
        run: PGDATABASE=nc_games_test PGUSER=mr_testerson PGPASSWORD=passw0rd npm test
